storePassword=wikdup@veedasip
keyPassword=wikdup@veedasip
keyAlias=veedasip-delivery
storeFile=/Users/apple/Downloads/cpp_modules/Veedasip/Vd_delivery_app/android/veedasip-delivery-key.jks
GOOGLE_MAPS_API_KEY=AIzaSyAYig-f-s8na0VmF_6S7we7n_XvMzBEfnI