List<Map<String, String>> infoList = [
  {
    'name': 'Jetha Lal',
    'location': 'GokulDham, Powder Gali, Mumbai',
    'time': '30 mins',
    'distance': '2.3',
    'price': '80',
    'items': '2',
  },
  {
    'name': 'Jetha Lal',
    'location': 'GokulDham, Powder Gali, Mumbai',
    'time': '30 mins',
    'distance': '2.3',
    'price': '80',
    'items': '2',
  },
  {
    'name': 'Jetha Lal',
    'location': 'GokulDham, Powder Gali, Mumbai',
    'time': '30 mins',
    'distance': '2.3',
    'price': '80',
    'items': '2',
  },
  {
    'name': 'Jetha Lal',
    'location': 'GokulDham, Powder Gali, Mumbai',
    'time': '30 mins',
    'distance': '2.3',
    'price': '80',
    'items': '2',
  },
  {
    'name': 'Jetha Lal',
    'location': 'GokulDham, Powder Gali, Mumbai',
    'time': '30 mins',
    'distance': '2.3',
    'price': '80',
    'items': '2',
  },
  {
    'name': 'Jetha Lal',
    'location': 'GokulDham, Powder Gali, Mumbai',
    'time': '30 mins',
    'distance': '2.3',
    'price': '80',
    'items': '2',
  },
];
